name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install numpy first to ensure correct version
          pip install "numpy<2.0.0"
          pip install -r requirements.txt
          # Verify versions
          pip list | grep -E "numpy|onnx|onnxruntime"

      - name: Run unit tests
        run: pytest -q